[[hooks]]
stage = "build"
command = "echo"
command_arguments = ["Building XForce Analytics Frontend..."]

[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["dist"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

[[proxy]]
backend = "http://localhost:3000/api/"
rewrite = "/api/"
